"""现有数据库 schema 基线。

Revision ID: 0001
Revises:
Create Date: 2026-08-11
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("input_url", sa.String(length=1000), nullable=False),
        sa.Column("normalized_url", sa.String(length=1000), nullable=False),
        sa.Column("active_key", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_stage", sa.String(length=40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("report_path", sa.String(length=1000), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_key"),
    )
    op.create_index(
        op.f("ix_scan_runs_current_stage"), "scan_runs", ["current_stage"], unique=False
    )
    op.create_index(
        op.f("ix_scan_runs_normalized_url"), "scan_runs", ["normalized_url"], unique=False
    )
    op.create_index(op.f("ix_scan_runs_status"), "scan_runs", ["status"], unique=False)
    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_base_url"), "targets", ["base_url"], unique=True)
    op.create_index(op.f("ix_targets_name"), "targets", ["name"], unique=True)
    op.create_index(op.f("ix_targets_owner"), "targets", ["owner"], unique=False)
    op.create_index(op.f("ix_targets_status"), "targets", ["status"], unique=False)
    op.create_index(op.f("ix_targets_type"), "targets", ["type"], unique=False)
    op.create_table(
        "credential_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=False),
        sa.Column("auth_type", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=False),
        sa.Column("login_config_path", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id", "name", name="uq_credential_profiles_target_name"),
    )
    op.create_index(
        op.f("ix_credential_profiles_auth_type"), "credential_profiles", ["auth_type"], unique=False
    )
    op.create_index(
        op.f("ix_credential_profiles_name"), "credential_profiles", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_credential_profiles_role"), "credential_profiles", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_credential_profiles_target_id"), "credential_profiles", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_credential_profiles_username"), "credential_profiles", ["username"], unique=False
    )
    op.create_table(
        "scan_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("asset_type", sa.String(length=40), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_run_id", "asset_type", "url"),
    )
    op.create_index(op.f("ix_scan_assets_asset_type"), "scan_assets", ["asset_type"], unique=False)
    op.create_index(
        op.f("ix_scan_assets_scan_run_id"), "scan_assets", ["scan_run_id"], unique=False
    )
    op.create_table(
        "scan_failures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_failures_code"), "scan_failures", ["code"], unique=False)
    op.create_index(
        op.f("ix_scan_failures_scan_run_id"), "scan_failures", ["scan_run_id"], unique=False
    )
    op.create_index(op.f("ix_scan_failures_stage"), "scan_failures", ["stage"], unique=False)
    op.create_table(
        "scan_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("asset_ids", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_run_id", "dedup_key"),
    )
    op.create_index(op.f("ix_scan_findings_category"), "scan_findings", ["category"], unique=False)
    op.create_index(
        op.f("ix_scan_findings_confidence"), "scan_findings", ["confidence"], unique=False
    )
    op.create_index(
        op.f("ix_scan_findings_scan_run_id"), "scan_findings", ["scan_run_id"], unique=False
    )
    op.create_index(op.f("ix_scan_findings_severity"), "scan_findings", ["severity"], unique=False)
    op.create_table(
        "scan_run_stages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_run_id", "name"),
    )
    op.create_index(op.f("ix_scan_run_stages_name"), "scan_run_stages", ["name"], unique=False)
    op.create_index(
        op.f("ix_scan_run_stages_scan_run_id"), "scan_run_stages", ["scan_run_id"], unique=False
    )
    op.create_index(op.f("ix_scan_run_stages_status"), "scan_run_stages", ["status"], unique=False)
    op.create_table(
        "scan_evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["scan_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_evidence_asset_id"), "scan_evidence", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_scan_evidence_evidence_type"), "scan_evidence", ["evidence_type"], unique=False
    )
    op.create_index(
        op.f("ix_scan_evidence_scan_run_id"), "scan_evidence", ["scan_run_id"], unique=False
    )
    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scan_jobs_credential_profile_id"),
        "scan_jobs",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_scan_jobs_status"), "scan_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_scan_jobs_target_id"), "scan_jobs", ["target_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("scan_job_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("session_type", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_supported", sa.Boolean(), nullable=False),
        sa.Column("session_metadata_redacted", sa.JSON(), nullable=False),
        sa.Column("storage_ref", sa.String(length=500), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_credential_profile_id"),
        "auth_sessions",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_scan_job_id"), "auth_sessions", ["scan_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_session_type"), "auth_sessions", ["session_type"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_status"), "auth_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_auth_sessions_target_id"), "auth_sessions", ["target_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("credential_profile_id", sa.Integer(), nullable=True),
        sa.Column("auth_session_id", sa.Integer(), nullable=True),
        sa.Column("scan_job_id", sa.Integer(), nullable=True),
        sa.Column("detail_redacted", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_auth_session_id"), "audit_events", ["auth_session_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_credential_profile_id"),
        "audit_events",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_scan_job_id"), "audit_events", ["scan_job_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_status"), "audit_events", ["status"], unique=False)
    op.create_index(op.f("ix_audit_events_target_id"), "audit_events", ["target_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("check_name", sa.String(length=120), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("location_key", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("inventory_refs", sa.JSON(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("trigger_explanation", sa.Text(), nullable=False),
        sa.Column("false_positive_boundaries", sa.Text(), nullable=False),
        sa.Column("reproduction_notes", sa.Text(), nullable=False),
        sa.Column("remediation_notes", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_category"), "findings", ["category"], unique=False)
    op.create_index(op.f("ix_findings_check_name"), "findings", ["check_name"], unique=False)
    op.create_index(op.f("ix_findings_confidence"), "findings", ["confidence"], unique=False)
    op.create_index(
        op.f("ix_findings_credential_profile_id"),
        "findings",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_findings_dedup_key"), "findings", ["dedup_key"], unique=False)
    op.create_index(op.f("ix_findings_first_seen"), "findings", ["first_seen"], unique=False)
    op.create_index(op.f("ix_findings_job_id"), "findings", ["job_id"], unique=False)
    op.create_index(op.f("ix_findings_last_seen"), "findings", ["last_seen"], unique=False)
    op.create_index(op.f("ix_findings_location_key"), "findings", ["location_key"], unique=False)
    op.create_index(op.f("ix_findings_session_id"), "findings", ["session_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_index(op.f("ix_findings_target_id"), "findings", ["target_id"], unique=False)
    op.create_index(op.f("ix_findings_title"), "findings", ["title"], unique=False)
    op.create_table(
        "inventory_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("auth_session_id", sa.Integer(), nullable=False),
        sa.Column("scan_job_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_from_url", sa.String(length=500), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("max_depth", sa.Integer(), nullable=False),
        sa.Column("max_requests", sa.Integer(), nullable=False),
        sa.Column("delay_ms", sa.Integer(), nullable=False),
        sa.Column("include_rules", sa.JSON(), nullable=False),
        sa.Column("exclude_rules", sa.JSON(), nullable=False),
        sa.Column("pages_count", sa.Integer(), nullable=False),
        sa.Column("endpoints_count", sa.Integer(), nullable=False),
        sa.Column("parameters_count", sa.Integer(), nullable=False),
        sa.Column("annotations_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_runs_auth_session_id"),
        "inventory_runs",
        ["auth_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_runs_credential_profile_id"),
        "inventory_runs",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_runs_scan_job_id"), "inventory_runs", ["scan_job_id"], unique=False
    )
    op.create_index(op.f("ix_inventory_runs_status"), "inventory_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_inventory_runs_target_id"), "inventory_runs", ["target_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("inventory_run_id", sa.Integer(), nullable=True),
        sa.Column("finding_id", sa.Integer(), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("storage_ref", sa.String(length=500), nullable=False),
        sa.Column("preview_redacted", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("page_title", sa.String(length=255), nullable=True),
        sa.Column("http_method", sa.String(length=32), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_credential_profile_id"),
        "evidence",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_evidence_evidence_type"), "evidence", ["evidence_type"], unique=False)
    op.create_index(op.f("ix_evidence_finding_id"), "evidence", ["finding_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_inventory_run_id"), "evidence", ["inventory_run_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_job_id"), "evidence", ["job_id"], unique=False)
    op.create_index(op.f("ix_evidence_session_id"), "evidence", ["session_id"], unique=False)
    op.create_index(op.f("ix_evidence_target_id"), "evidence", ["target_id"], unique=False)
    op.create_index(op.f("ix_evidence_title"), "evidence", ["title"], unique=False)
    op.create_table(
        "finding_retests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("finding_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("credential_profile_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("inventory_run_id", sa.Integer(), nullable=True),
        sa.Column("scan_job_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_profile_id"],
            ["credential_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finding_retests_credential_profile_id"),
        "finding_retests",
        ["credential_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finding_retests_finding_id"), "finding_retests", ["finding_id"], unique=False
    )
    op.create_index(
        op.f("ix_finding_retests_inventory_run_id"),
        "finding_retests",
        ["inventory_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finding_retests_scan_job_id"), "finding_retests", ["scan_job_id"], unique=False
    )
    op.create_index(op.f("ix_finding_retests_status"), "finding_retests", ["status"], unique=False)
    op.create_index(
        op.f("ix_finding_retests_target_id"), "finding_retests", ["target_id"], unique=False
    )
    op.create_table(
        "inventory_annotations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inventory_run_id", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_ref", sa.String(length=500), nullable=False),
        sa.Column("marker", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_run_id",
            "subject_type",
            "subject_ref",
            "marker",
            name="uq_inventory_annotations_subject_marker",
        ),
    )
    op.create_index(
        op.f("ix_inventory_annotations_inventory_run_id"),
        "inventory_annotations",
        ["inventory_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_annotations_marker"), "inventory_annotations", ["marker"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_annotations_subject_ref"),
        "inventory_annotations",
        ["subject_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_annotations_subject_type"),
        "inventory_annotations",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "inventory_endpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inventory_run_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("cache_control", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("response_preview", sa.Text(), nullable=True),
        sa.Column("set_cookie_names", sa.JSON(), nullable=False),
        sa.Column("cookie_issue_flags", sa.JSON(), nullable=False),
        sa.Column("status_codes_observed", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_run_id", "method", "path", name="uq_inventory_endpoints_run_method_path"
        ),
    )
    op.create_index(
        op.f("ix_inventory_endpoints_inventory_run_id"),
        "inventory_endpoints",
        ["inventory_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_endpoints_method"), "inventory_endpoints", ["method"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_endpoints_path"), "inventory_endpoints", ["path"], unique=False
    )
    op.create_table(
        "inventory_pages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inventory_run_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("cache_control", sa.String(length=255), nullable=True),
        sa.Column("text_preview", sa.Text(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("first_visited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_visited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("visit_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inventory_run_id", "url", name="uq_inventory_pages_run_url"),
    )
    op.create_index(
        op.f("ix_inventory_pages_inventory_run_id"),
        "inventory_pages",
        ["inventory_run_id"],
        unique=False,
    )
    op.create_table(
        "inventory_parameters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inventory_run_id", sa.Integer(), nullable=False),
        sa.Column("inventory_endpoint_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_endpoint_id"],
            ["inventory_endpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_run_id"],
            ["inventory_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_parameters_inventory_endpoint_id"),
        "inventory_parameters",
        ["inventory_endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_parameters_inventory_run_id"),
        "inventory_parameters",
        ["inventory_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_parameters_name"), "inventory_parameters", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_parameters_source_type"),
        "inventory_parameters",
        ["source_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_parameters_source_type"), table_name="inventory_parameters")
    op.drop_index(op.f("ix_inventory_parameters_name"), table_name="inventory_parameters")
    op.drop_index(
        op.f("ix_inventory_parameters_inventory_run_id"), table_name="inventory_parameters"
    )
    op.drop_index(
        op.f("ix_inventory_parameters_inventory_endpoint_id"), table_name="inventory_parameters"
    )
    op.drop_table("inventory_parameters")
    op.drop_index(op.f("ix_inventory_pages_inventory_run_id"), table_name="inventory_pages")
    op.drop_table("inventory_pages")
    op.drop_index(op.f("ix_inventory_endpoints_path"), table_name="inventory_endpoints")
    op.drop_index(op.f("ix_inventory_endpoints_method"), table_name="inventory_endpoints")
    op.drop_index(op.f("ix_inventory_endpoints_inventory_run_id"), table_name="inventory_endpoints")
    op.drop_table("inventory_endpoints")
    op.drop_index(op.f("ix_inventory_annotations_subject_type"), table_name="inventory_annotations")
    op.drop_index(op.f("ix_inventory_annotations_subject_ref"), table_name="inventory_annotations")
    op.drop_index(op.f("ix_inventory_annotations_marker"), table_name="inventory_annotations")
    op.drop_index(
        op.f("ix_inventory_annotations_inventory_run_id"), table_name="inventory_annotations"
    )
    op.drop_table("inventory_annotations")
    op.drop_index(op.f("ix_finding_retests_target_id"), table_name="finding_retests")
    op.drop_index(op.f("ix_finding_retests_status"), table_name="finding_retests")
    op.drop_index(op.f("ix_finding_retests_scan_job_id"), table_name="finding_retests")
    op.drop_index(op.f("ix_finding_retests_inventory_run_id"), table_name="finding_retests")
    op.drop_index(op.f("ix_finding_retests_finding_id"), table_name="finding_retests")
    op.drop_index(op.f("ix_finding_retests_credential_profile_id"), table_name="finding_retests")
    op.drop_table("finding_retests")
    op.drop_index(op.f("ix_evidence_title"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_target_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_session_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_job_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_inventory_run_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_finding_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_evidence_type"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_credential_profile_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_inventory_runs_target_id"), table_name="inventory_runs")
    op.drop_index(op.f("ix_inventory_runs_status"), table_name="inventory_runs")
    op.drop_index(op.f("ix_inventory_runs_scan_job_id"), table_name="inventory_runs")
    op.drop_index(op.f("ix_inventory_runs_credential_profile_id"), table_name="inventory_runs")
    op.drop_index(op.f("ix_inventory_runs_auth_session_id"), table_name="inventory_runs")
    op.drop_table("inventory_runs")
    op.drop_index(op.f("ix_findings_title"), table_name="findings")
    op.drop_index(op.f("ix_findings_target_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_session_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_location_key"), table_name="findings")
    op.drop_index(op.f("ix_findings_last_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_job_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_first_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_dedup_key"), table_name="findings")
    op.drop_index(op.f("ix_findings_credential_profile_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_confidence"), table_name="findings")
    op.drop_index(op.f("ix_findings_check_name"), table_name="findings")
    op.drop_index(op.f("ix_findings_category"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_audit_events_target_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_status"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_scan_job_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_credential_profile_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_auth_session_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_auth_sessions_target_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_status"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_session_type"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_scan_job_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_credential_profile_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_scan_jobs_target_id"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_status"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_credential_profile_id"), table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index(op.f("ix_scan_evidence_scan_run_id"), table_name="scan_evidence")
    op.drop_index(op.f("ix_scan_evidence_evidence_type"), table_name="scan_evidence")
    op.drop_index(op.f("ix_scan_evidence_asset_id"), table_name="scan_evidence")
    op.drop_table("scan_evidence")
    op.drop_index(op.f("ix_scan_run_stages_status"), table_name="scan_run_stages")
    op.drop_index(op.f("ix_scan_run_stages_scan_run_id"), table_name="scan_run_stages")
    op.drop_index(op.f("ix_scan_run_stages_name"), table_name="scan_run_stages")
    op.drop_table("scan_run_stages")
    op.drop_index(op.f("ix_scan_findings_severity"), table_name="scan_findings")
    op.drop_index(op.f("ix_scan_findings_scan_run_id"), table_name="scan_findings")
    op.drop_index(op.f("ix_scan_findings_confidence"), table_name="scan_findings")
    op.drop_index(op.f("ix_scan_findings_category"), table_name="scan_findings")
    op.drop_table("scan_findings")
    op.drop_index(op.f("ix_scan_failures_stage"), table_name="scan_failures")
    op.drop_index(op.f("ix_scan_failures_scan_run_id"), table_name="scan_failures")
    op.drop_index(op.f("ix_scan_failures_code"), table_name="scan_failures")
    op.drop_table("scan_failures")
    op.drop_index(op.f("ix_scan_assets_scan_run_id"), table_name="scan_assets")
    op.drop_index(op.f("ix_scan_assets_asset_type"), table_name="scan_assets")
    op.drop_table("scan_assets")
    op.drop_index(op.f("ix_credential_profiles_username"), table_name="credential_profiles")
    op.drop_index(op.f("ix_credential_profiles_target_id"), table_name="credential_profiles")
    op.drop_index(op.f("ix_credential_profiles_role"), table_name="credential_profiles")
    op.drop_index(op.f("ix_credential_profiles_name"), table_name="credential_profiles")
    op.drop_index(op.f("ix_credential_profiles_auth_type"), table_name="credential_profiles")
    op.drop_table("credential_profiles")
    op.drop_index(op.f("ix_targets_type"), table_name="targets")
    op.drop_index(op.f("ix_targets_status"), table_name="targets")
    op.drop_index(op.f("ix_targets_owner"), table_name="targets")
    op.drop_index(op.f("ix_targets_name"), table_name="targets")
    op.drop_index(op.f("ix_targets_base_url"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_scan_runs_status"), table_name="scan_runs")
    op.drop_index(op.f("ix_scan_runs_normalized_url"), table_name="scan_runs")
    op.drop_index(op.f("ix_scan_runs_current_stage"), table_name="scan_runs")
    op.drop_table("scan_runs")
    # ### end Alembic commands ###
